hydra:
  run:
    dir: ${log_output_dir}
  output_subdir: code/hydra # Store hydra's config breakdown here for debugging
  searchpath: # Only <exp_dir> in these paths are discoverable
    - pkg://autoware_ml.configs

defaults:
  - database: nuscenes/nuscenes_base
  - datamodule: nuscenes/default_nuscenes_detection3d_datamodule
  - override hydra/hydra_logging: none # Disable hydra's logging
  - _self_

# Common settings
# [x_min, y_min, z_min, x_max, y_max, z_max], matching the standard NuScenes detection3d benchmark range
point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]

# Directory structure
date_format: "%Y.%m.%d.%H.%M.%S"
experiment_uid: ${now:${date_format}} # Unique Id of the experiment, default to timestamp
log_output_dir: outputs/annotations/${experiment_uid}
data_root_path: data
working_dir: /workspace
cache_root_path: ${data_root_path}/cache/
